[env:esp32s3]
platform = espressif32 @ 6.5.0
board = exlink_esp32s3_16mb
framework = arduino
board_build.arduino.partitions = my.csv
board_build.arduino.memory_type = qio_qspi
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
lib_extra_dirs = D:/ESP32/exlink/lib
build_flags =
  -DUSER_SETUP_LOADED
  -include tft_setup_gc9307.h
  -std=gnu++17
  -Iinclude
  -ID:/ESP32/exlink/lib/TFT_eSPI
  -Isrc
  -Isrc/display
  -Isrc/flash
  -Isrc/hal
  -Isrc/network
  -Isrc/storage
  -Isrc/web
monitor_speed = 115200
upload_speed = 460800
